### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by Kbishou** [thasorn/Q4Care#1]
hi @thasorn  , im sorry to make an issue here about  another project . I noticed that you did a nice recurrence  work on  LiDan456/GAN-AD ,and Im quite interested in it . However , I get some trouble on running the code ,since I cannot find any .csv and .npy dataset in the Swat dataset downloaded from https://itrust.sutd.edu.sg/itrust-labs_datasets/. Could you tall me how to get the swat.csv and swat.npy file , and  meybe you can send these to me ? Thank you for your generosity.

![image](https://user-images.githubusercontent.com/54734032/91926183-3c470f80-ed09-11ea-8ff8-a9d407b17149.png)

![image](https://user-images.githubusercontent.com/54734032/91926226-55e85700-ed09-11ea-9d86-2d29e49312b6.png)

**Comment by thasorn** [comment]
Dear @Kbishou ,

Unfortunately, due to iTrust dataset terms and conditions, I am not eligible to provided or redistributed SWaT dataset itself or modified one without permission from iTrust.

However, I will try to help you as much as I could by give a quick guide on how to start implement dataset into GAN-AD model, but please noted that I have not work on GAN-AD over a year, also the result that I received was not matched with the result that reported in paper, so please be noted that I might did something wrong or misremembering something. I will not be responsible for any mistake that could happened to your work or project. Please be warned.

What I remembered:

1. Go to SWaT.A1 & A2_Dec 2015 -> Physical -> Download SWaT dataset csv file. (Depends on what domain you are interested or try to train model right now. Normal data or Attacked data)
2. Adjust and clean dataset. (I cannot remember properly, but there might be some data missing values or you have to remove any space in csv file. Make all data close to cell boundary. )
3. Save your csv file into the folder that GAN-AD will pick up the file for running.
4. Run the code. Check any error that could happened. (Based on my experience, GAN-AD code still have some error or bug that required to be fixed. Some are typo some are code logic, but it should not be too complicated)
5. You should be able to run GAN-AD model now. (Do not forget to look at the document from GAN-AD itself if you have any problem running)

Note:
You might wonder where npy file is. GAN-AD will automatically generate it once you run the command correctly.

Lastly, I will close this issue for now, since this is not a suitable section to ask about other project. A question about "ABC" project should be an issue for "ABC"'s Github repository, not only a better chance that you will received a help from a professional or someone that current work on that project, but also another people who face the same problem like you will find a solution quicker. I love your enthusiasm to solved the problem as fast as possible, but at the same time, there is some Github's practice and regulation that should be consider for better project management.

Hope you understand and very best of luck to your project. 

Cheers!

C. Thasorn

**Comment by Kbishou** [comment]
Dear @thasorn :
Thank you for your reply and please forgive my breaking regulation. The last question is , I only find the .xlsx file but not the .csv file(see the attached image）.  Has iTrust changed the format? Can i convert the .xlsx file to .csv file manually? Thanks again.
best wishes
KB.

![image](https://user-images.githubusercontent.com/54734032/91967042-3f5ff100-ed45-11ea-8048-79bfd53f7e38.png)

**Comment by thasorn** [comment]
Dear @Kbishou ,

You can convert .xlsx file to .csv file manually by open .xlsx file and save as .csv file (Before you save as, under the changing file name textbox, there should be a dropdown box that allow you to choose file type .csv). 

Cheers! ,

C. Thasorn

**Comment by Kbishou** [comment]
Dear @thasorn 
Sorry for disturbing you again. Did you get this issue (see attached image) when running "python RGAN.py --settings_file swat_gen"? It puzzles me for days. Do you know how to fix it?
Best wishes
KB
![image](https://user-images.githubusercontent.com/54734032/92481793-6f156a00-f219-11ea-8f33-b058e16a167a.png)
